@startuml
skinparam monochrome false
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD)

' File sytling 

'alt sytling
skinparam SequenceGroupHeaderFontColor green
skinparam SequenceGroupFontColor blue
skinparam SequenceGroupFontSize 15
'Middle text styling
'skinparam sequenceMessageAlign center
'skinparam sequenceMessageAlign direction
autonumber

actor "Property Owner" as PO  #RosyBrown
 
participant ":System" as System

activate PO
        PO -> System : asks to listing a property
    activate System
    
        System --> PO : shows the list of agencies available and asks to select one
    deactivate System
    
        PO -> System : selects a agency
    activate System

        System --> PO : shows the list of agents available and asks to select one or use a feature to select a random agent
    deactivate System
    autonumber 5.1
    alt Select a agent
            PO -> System : selects a agent

    else random feature
            PO -> System : randomly assing one agent
    end
    autonumber 6

    System --> PO : requests the property address (i.e. street,city,district,state,zipcode)
    deactivate System

        PO -> System : types the requested data
    activate System

    loop selectiong one or more photos
        System --> PO : requests photos (i.e photoURL)
    deactivate System

        PO -> System : types the requested data
    activate System
    end

        System --> PO : requests the type of property 
    deactivate System

        'if statement
        alt Property is a land

            autonumber 11 
            PO -> System : types requested data
            
            System-->PO : request the Land characteristics

            PO -> System : types requested data

        else Property is a appartement
            
            autonumber 11
            PO -> System : types requested data

            System-->PO : request the appartement characteristics

            PO -> System : types requested data
        loop select one or more equipments
            System-->PO : request available equipment
            PO -> System : types requested data
        end 
        else Property is a house

            autonumber 11
            PO -> System : types requested data
            System-->PO : request the House characteristics

            PO -> System : types requested data

            loop select one or more equipments
            System-->PO : request available equipment
            PO -> System : types requested data
        end 
        end
        System -->PO : request the dealType

        PO ->System : types requested data

        alt Deal is Sale

        System-->PO : request the price
        PO ->System : types requested data
        else Deal is Rent
                autonumber 18
        System-->PO : request the contract duration
        PO -> System : types requested data
        end

        System --> PO : shows the data and asks to confirmation
    deactivate System

        PO -> System : confirms the data
    activate System

    'Final Part
        System --> PO : Displays operation success
    deactivate System

@enduml