@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "System Administrator" as Employee
participant ":System" as System

activate Employee

   Employee -> System : asks to register a new employee
   activate System

       System --> Employee : requests data(name, citizen card number, \ntax number, adress, email, \nphone number, agency)
   deactivate System

   Employee -> System : types requested data
   activate System

       System --> Employee : shows roles category list and ask to select one
   deactivate System

   Employee -> System : selects a role category
   activate System

       System --> Employee : shows all data and requests confirmation
   deactivate System

   Employee -> System : confirms data
   activate System

       System --> Employee :informs operation success
   deactivate System
@enduml