@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "Agent" as A #RosyBrown
participant ":VerifyAnnouncementUI" as UI
participant ":CheckOrdersController" as CTRL
participant "Message" as Message
participant "AgentSession" as US
participant ":Repositories" as RepositorySingleton
participant "repositories\n:Repositories" as PLAT
participant "AnnouncementRepository" as AnnouncementRepository

activate A

A -> UI : asks check orders from a property
activate UI

UI -> CTRL** : create
UI -> CTRL : getAnnouncementsByOrder()
activate CTRL

CTRL -> RepositorySingleton : getInstance()
activate RepositorySingleton

RepositorySingleton --> CTRL: repositories
deactivate RepositorySingleton

CTRL -> PLAT : getAnnouncementRepository()
activate PLAT

PLAT --> CTRL: AnnouncementRepository
deactivate PLAT

CTRL -> AnnouncementRepository : getAnnouncementList()
activate AnnouncementRepository

AnnouncementRepository --> CTRL : announcementList
deactivate AnnouncementRepository

CTRL -> CTRL: sort announcements by ascending date
CTRL-->Mapper:toDTO(announcementList)
activate Mapper

Mapper -> Mapper : AnnouncementListDto:List<AnnouncementDTO> = toDTO(announcementList))
activate Mapper

deactivate Mapper

Mapper --> CTRL : AnnouncementListDto
deactivate Mapper

deactivate Mapper

CTRL --> UI : announcementListDto
deactivate CTRL

UI --> A : shows all announcements by order
deactivate UI

A -> UI : chose one announcement
activate UI

UI -> CTRL : getOrdersByOrder(announcementDto)
activate CTRL

CTRL -> CTRL: getOrders()
CTRL -> CTRL: sort orders by ascending price
activate Mapper

CTRL --> Mapper : toDTO(orderList)
Mapper -> Mapper : OrderListDto:List<OrderDTO> = toDTO(orderList))
activate Mapper

deactivate Mapper

Mapper --> CTRL : OrderListDto
deactivate Mapper

deactivate Mapper
CTRL --> UI:OrderListDto
deactivate CTRL

UI --> A: shows all orders by order
deactivate UI

A -> UI: chose one order
activate UI

UI --> A: shows the validate options (Accept/Denied/Redo)
A -> UI: chose one option


alt option = Accept

UI -> CTRL : acceptThisOrder(announcementDto, orderDto)
activate CTRL

CTRL -> CTRL : new Message(true, subject, announcement.getRequest().getEmployee(), announcement.getRequest().getUser(), inf)
CTRL -> CTRL : message.sendEmail()
CTRL -> CTRL : message.saveEmail()
deactivate CTRL

else option = Denied

UI -> CTRL : removeThisOrder(announcementDto, orderDto)
activate CTRL
CTRL -> CTRL : new Message(true, subject, announcement.getRequest().getEmployee(), announcement.getRequest().getUser(), inf)
CTRL -> CTRL : message.send()
CTRL -> CTRL : message.save()
deactivate CTRL
else option = Skip

UI -> UI : new CheckOrderUI.run()
end

deactivate A
@enduml
