@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

'hide footbox
actor "System Administrator" as ADM
participant ":RegisterEmployeeUI" as UI
participant ":RegisterEmployeeController" as CTRL
participant "Repositories" as RE
participant "employeeRepository : EmployeeRepository" as ER
participant "employee: Employee" as E
participant "RoleRepository" as RR

activate ADM

ADM -> UI : register an employee
activate UI

UI --> ADM : requests data(name, citizen card number, \ntax number, adress, email, \nphone number, agency)
deactivate UI

ADM -> UI : types requested data
activate UI

UI -> CTRL :registerEmployee(name,citizenCardNumber,taxNumber,address,email,phoneNumber,agencyDesignation)
activate CTRL

CTRL -> RE : repository = getEmployeeRepository()

CTRL -> ER : employee = registerEmployee(name,citizenCardNumber,taxNumber,address,email,phoneNumber,agencyDesignation)
activate ER

ER -> E** : create(name,citizenCardNumber,taxNumber,address,email,phoneNumber,agencyDesignation)
deactivate ER

CTRL -> ER : validateRegisterEmployee(employee)
activate ER
deactivate ER
deactivate CTRL

UI --> ADM : shows employee role list and asks to select one
deactivate ER

deactivate UI

ADM -> UI : selects an employee role
activate UI

UI -> CTRL : employeeRoles = getRoleList()
activate CTRL

CTRL -> ER : RoleRepository = getRoleRepository()
activate ER
deactivate ER

CTRL -> RR : getEmployeeRoles
deactivate CTRL
deactivate UI


ADM -> UI : confirms the data
activate UI

UI -> CTRL :saveEmployee()
activate CTRL

CTRL -> ER : saveEmployee(employee)
activate ER

ER -> ER : validateEmployee(employee)
activate ER
deactivate ER

ER -> ER : addEmployee(employee)
activate ER
deactivate ER

CTRL --> UI : result
UI --> ADM : informs operation sucess

deactivate ER
deactivate CTRL
deactivate  UI
deactivate ADM


@enduml